- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: install | Installing Pre-Reqs
      apt:
        name: "{{ item }}"
        state: "present"
      with_items:
        - 'build-essential'
        - 'libffi-dev'
        - 'libssl-dev'
        - 'python-dev'
        - 'python3-setuptools'
        - 'python3-pip'

